# Generated by Django 6.0.4 on 2026-04-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='default_general_service_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='garage_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='garage_timing',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
