# Generated by Django 5.2.14 on 2026-06-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('general_service', 'General Service'), ('oil_change', 'Oil Change'), ('ac_service', 'AC Service'), ('brake_service', 'Brake Service'), ('wash', 'Car Wash'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=40)),
                ('booking_date', models.DateField(db_index=True)),
                ('time_slot', models.TimeField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['booking_date', 'time_slot'],
            },
        ),
    ]
